name: actions_test

on: 
  push:
    branches:
      - '*'

    tags-ignore:
      - refs/heads/*

  pull_request:
    branches:
      - master
  

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.6]
        python-arch: ["x86", "x64"]

    env:
      PYTHONHASHSEED: 32
      TZ: 'Asia/Shanghai'

    runs-on: ubuntu-latest
    
    steps:
    - name: checkuot
      uses: actions/checkout@v1
        
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

  deploy:
    env:
      PYTHONHASHSEED: 32
      TZ: 'Asia/Shanghai'

    runs-on: ubuntu-latest
    
    steps:
    - name: checkuot
      uses: actions/checkout@v1
        
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "deploy haha"