name: actions_test

on: [push]

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.6]
        python-arch: ["x86"]

    env:
      PYTHONHASHSEED: 32
      TZ: 'Asia/Shanghai'

    runs-on: ubuntu-latest
    
    steps:
    - name: checkuot
      uses: actions/checkout@v1
        
    - name: Install dependencies
      timeout-minutes: 1
      run: |
        echo sleep 60s
        sleep 2m

    - name: Install dependencies
      if: always()
      run: |
        sleep 30
        echo iam alive        
        