name: actions_test

on: [push]

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.6]
        python-arch: ["x86"]

    env:
      PYTHONHASHSEED: 32
      TZ: "UTC-8"

    runs-on: windows-latest

    steps:
    - name: Create log file name
      id: get_log_name
      run: |
        #date=$(date -d today +%Y%m%d)
        #version=$(git rev-parse --short HEAD)
        #log=$date_$version.log
        #log2=$date_$version.log
        #LOG_FILE=$($(date -d today +%Y%m%d)_${{matrix.python-version}}_${{matrix.python-arch}}_$(git rev-parse --short HEAD).log)
        
        file1="$(%date:~10,4%%date:~7,2%%date:~4,2%)\
        _${{matrix.python-version}}_${{matrix.python-arch}}_.log"
        file2="$(date -d today +%Y%m%d) \
        _${{matrix.python-version}}_${{matrix.python-arch}}_.log"
        file3="$(date -d today +%Y%m%d) ^
        _${{matrix.python-version}}_${{matrix.python-arch}}_.log"

        echo $file1
        echo $file2
        echo $file3
 
