name: actions_test

on: [push]

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.6]
        python-arch: ["x86"]

    env:
      PYTHONHASHSEED: 32
      TZ: "UTC-8"

    runs-on: windows-latest

    steps:
    - name: Create log file name
      id: get_log_name
      run: |
        LOG_FIL: $(date -d today +%Y%m%d)_${{matrix.python-version}}_${{matrix.python-arch}}.log
        echo "::set-output name=file::$LOG_FILE"        

    - name: Run Test Case
      run: |
        echo ${{steps.get_log_name.outputs.file}}
  