name: actions_test

on: [push]

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.6]
        python-arch: ["x86"]

    env:
      PYTHONHASHSEED: 32
      TZ: "UTC-8"

    runs-on: windows-latest
    
    steps:
    - name: Setup Python ${{matrix.python-version}} ${{matrix.python-arch}}
      uses: actions/setup-python@v1
      with:
        python-version: ${{matrix.python-version}}
        architecture: ${{matrix.python-arch}}
        
    - name: Install dependencies
      run: |
        pip install zip-files
        mkdir ./log/20200119 -p
        touch ./log/20200119/res.log
        zip-folder -a -o report.zip ./log
        