name: actions_test

on: [push]

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.6]
        python-arch: ["x86"]

    env:
      PYTHONHASHSEED: 32
      TZ: "UTC-8"

    runs-on: windows-latest

    steps:
    - name: Create log file name
      id: get_log_name
      run: |
        #date=$(date -d today +%Y%m%d)
        #version=$(git rev-parse --short HEAD)
        #log=$date_$version.log
        #log2=$date_$version.log
        file0=$($(date -d today +%Y%m%d)_${{matrix.python-version}}_${{matrix.python-arch}}.log)
        
        file1="$(date -d today +%Y%m%d)\
        _${{matrix.python-version}}_${{matrix.python-arch}}_.log"

        echo $file0
        echo $file1
 
