name: actions_test

on: 
  push:
    branches:
      - '*'

    tags-ignore:
      - refs/heads/*

  pull_request:
    branches:
      - master
  

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: 3.6.x
            python-arch: ["x64"]

          - os: windows-latest
            python-version: 3.6.x
            python-arch: ["x86", "x64"]

    env:
      PYTHONHASHSEED: 32
      TZ: 'Asia/Shanghai'
    
    steps:
    - name: checkuot
      uses: actions/checkout@v1
        
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo ${{ matrix.os }} ${{ matrix.python-arch }}