name: actions_test

on: 
  push:
    branches:
      - '*'

    tags-ignore:
      - refs/heads/*

  pull_request:
    branches:
      - master
  

jobs:
  build:
    strategy:
      matrix:
        envinfo:
          - { os: ubuntu-latest, python-version: 3.6.x, python-arch: x64, STH: "linux-3.6-x64" }
          
    env:
      PYTHONHASHSEED: 32
      TZ: 'Asia/Shanghai'
      STH: ${{ matrix.envinfo.STH }}
      LOG_PATH: './log_archive/'
      REF: ${{ github.ref }}
      REF2: ${{ github.sha }}
      REFNAME: $(echo ${{ github.ref }}#refs/heads/})
      DATE: $(date -d today +%Y%m%d)

    runs-on: ${{ matrix.envinfo.os }}

    steps:
    - name: checkuot
      uses: actions/checkout@v1
        
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo ${{ matrix.envinfo.os }} ${{ env.LOG_PATH }}

    - name: Setup branch AWS S3 docs path
      if: startsWith(github.event.ref, 'refs/heads')
      run: |
        echo "::set-env name=DEST_DIR_DIST::docs/tqsdk-python/$(echo ${GITHUB_REF#refs/heads/})/"

    - name: Publish tag build/doc to AWS S3
      if: github.event_name != 'pull_request'
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --exclude '.doctrees/*'
      env:
        AWS_S3_BUCKET: ${{ secrets.BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: "build/doc"
        DEST_DIR: DEST_DIR_DIST
        DEST_DIR: ${ DEST_DIR_DIST }