name: actions_test

on: 
  push:
    branches:
      - '*'

    tags-ignore:
      - refs/heads/*

  pull_request:
    branches:
      - master
  

jobs:
  build:
    strategy:
      matrix:
        envinfo:
          - { os: ubuntu-latest, python-version: 3.6.x, python-arch: x64, STH: "linux-3.6-x64" }
          
    env:
      PYTHONHASHSEED: 32
      TZ: 'Asia/Shanghai'
      STH: ${{ matrix.envinfo.STH }}
      LOG_PATH: './log_archive/'
      REF: ${{ github.ref }}
      REF2: ${{ github.sha }}
      REFNAME: $(echo ${{ github.ref }}#refs/heads/})
      DATE: $(date -d today +%Y%m%d)

    runs-on: ${{ matrix.envinfo.os }}

    steps:
    - name: checkuot
      uses: actions/checkout@v1

    - name: file size list
      id: file-size-check
      run: |
        git ls-files | xargs ls -l | sort -nrk5 | awk '{if($5 > ${{ secrets.FILE_LIMIT_SIZE }}) print $9}' | xargs ls -lrth'
        echo "::set-output name=LARGE-FILES-COUNT::$(git ls-files | xargs ls -l | sort -nrk5 | awk '{if($5 > ${{ secrets.FILE_LIMIT_SIZE }}) print $0}' | wc -l)"

    - if: steps.file-size-check.outputs.LARGE-FILES-COUNT != 0
      run: |
        echo "file size check failed"
        exit 1

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo ${{ matrix.envinfo.os }} ${{ env.LOG_PATH }}

    - name: Setup branch AWS S3 docs path
      if: startsWith(github.event.ref, 'refs/heads')
      run: |
        echo "::set-env name=DEST_DIR_DIST::docs/tqsdk-python/$(echo ${GITHUB_REF#refs/heads/})/"
