name: actions_test

on: [push]

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.6]
        python-arch: ["x86"]

    env:
      PYTHONHASHSEED: 32
      TZ: "UTC-8"

    runs-on: windows-latest

    steps:
    - name: Create log file name
      id: get_log_name
      run: |
        echo $github.sha
        echo $github.workflow