name: actions_test

on: 
  push:
    branches:
      - '*'

    tags-ignore:
      - refs/heads/*

  pull_request:
    branches:
      - master
  

jobs:
  build:
    strategy:
      matrix:
        envinfo:
          - { os: ubuntu-latest, python-version: 3.6.x, python-arch: x64, STH: "linux-3.6-x64" }
          - { os: windows-latest, python-version: 3.6.x, python-arch: x86, STH: "windows-3.6-x86" } 
          - { os: windows-latest, python-version: 3.6.x, python-arch: x64, STH: "windows-3.6-x64" } 

    env:
      PYTHONHASHSEED: 32
      TZ: 'Asia/Shanghai'
      STH: ${{ matrix.envinfo.STH }}
      LOG_PATH: './log_archive/'
      REF: ${{ github.event.ref }}
      REF1: ${{ github.event.ref#refs/heads/ }}

    runs-on: ${{ matrix.envinfo.os }}

    steps:
    - name: checkuot
      uses: actions/checkout@v1
        
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo ${{ matrix.envinfo.os }} ${{ env.LOG_PATH }}