name: actions_test

on: [push]

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.6]
        python-arch: ["x86"]

    env:
      PYTHONHASHSEED: 32
      TZ: "UTC-8"

    runs-on: windows-latest

    steps:
    - name: Create log file name
      id: log_name
      run: |
        echo "::set-output name=log_path::./log/$(date -d today +%Y%m%d)/"
        echo "::set-output name=log_name::win${{matrix.python-version}}_${{matrix.python-arch}}"


    - name: show name
      run: |
        echo ${{steps.log_name.outputs.log_path}}
        echo ${{steps.log_name.outputs.log_name}}